In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
Textual_Data = pd.read_csv("Dataset/Non_Invasive_Anemia_Dataset.csv")  
Textual_Data.head()

,Subject_ID,Image_ID_Conjunctiva,Image_ID_Palm,Image_ID_Nail,HB_LEVEL,SEVERITY,Age(Months),Age (Years),GENDER,TYPE,COUNTRY,Data_Type
0,ID0001,Image_0001_C,Image_0001_P,Image_0001_N,9.8,Moderate,6,0.5,Female,Anemic,Ghana,NaN
1,ID0002,Image_0002_C,Image_0002_P,Image_0002_N,9.9,Moderate,24,2.0,Male,Anemic,Ghana,NaN
2,ID0003,Image_0003_C,Image_0003_P,Image_0003_N,11.1,Non-Anemic,24,2.0,Female,Non-Anemic,Ghana,NaN
3,ID0004,Image_0004_C,Image_0004_P,Image_0004_N,12.5,Non-Anemic,12,1.0,Male,Non-Anemic,Ghana,NaN
4,ID0005,Image_0005_C,Image_0005_P,Image_0005_N,9.9,Moderate,24,2.0,Male,Anemic,Ghana,NaN

In [7]:
le = LabelEncoder()
df['gender_encoded'] = le.fit_transform(df['GENDER'])  # Female=1, Male=0

In [8]:
df.head()

,Subject_ID,Image_ID_Conjunctiva,Image_ID_Palm,Image_ID_Nail,HB_LEVEL,SEVERITY,Age(Months),Age (Years),GENDER,TYPE,COUNTRY,Data_Type,gender_encoded
0,ID0001,Image_0001_C,Image_0001_P,Image_0001_N,9.8,Moderate,6,0.5,Female,Anemic,Ghana,NaN,0
1,ID0002,Image_0002_C,Image_0002_P,Image_0002_N,9.9,Moderate,24,2.0,Male,Anemic,Ghana,NaN,1
2,ID0003,Image_0003_C,Image_0003_P,Image_0003_N,11.1,Non-Anemic,24,2.0,Female,Non-Anemic,Ghana,NaN,0
3,ID0004,Image_0004_C,Image_0004_P,Image_0004_N,12.5,Non-Anemic,12,1.0,Male,Non-Anemic,Ghana,NaN,1
4,ID0005,Image_0005_C,Image_0005_P,Image_0005_N,9.9,Moderate,24,2.0,Male,Anemic,Ghana,NaN,1

In [10]:
scaler = StandardScaler()
df['age_scaled'] = scaler.fit_transform(df[['Age (Years)']])

In [11]:
text_features = df[['age_scaled', 'gender_encoded']].to_numpy()

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

def build_text_mlp(input_dim=2, output_dim=32):
    inputs = tf.keras.Input(shape=(input_dim,))
    x = layers.Dense(16, activation='relu')(inputs)
    x = layers.Dense(output_dim, activation='relu')(x)
    model = models.Model(inputs=inputs, outputs=x)
    return model

text_model = build_text_mlp()
text_feature_vector = text_model(text_features)  # shape: (num_samples, 32)
print(text_feature_vector.shape)

(1607, 32)

: